# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Generate Python Docs

on:
  push:
    branches:
      - master
      - addPythonDocs
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version}}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Generate Docs
        run: |
          #Create virtual environment
            python -m venv venv
          #Activate virtual environment
            source venv/bin/activate
          #Install dependencies
           python -m pip install python-dotenv
           pip install -r requirements.txt
           pdoc --html --output-dir ./docs ./ringcentral

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
